// /src/app/layout.tsx
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import ClientProvider from "../components/ClientLayout"; // Ensure the import path is correct
import { ToastContainer } from 'react-toastify'; // Import ToastContainer

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen dark bg-background font-sans antialiased", fontSans.variable)}>
        <ClientProvider>
          {children}
        </ClientProvider>
        <ToastContainer /> {/* Add ToastContainer here */}
      </body>
    </html>
  );
}
